ships:
  mining:
    - "STARSTAR-2"

actions: # actions are per ship
  mine: # Definition of the action "mine"
    steps:
      - orbit
      - extract:
          fail-fast: false
      - dock
      - navigate:
          destination:
            trait: "MARKETPLACE"
      - dock
      - refuel
      - sellall
      - navigate:
          destination:
            type: "ASTEROID_FIELD"
      - refuel

triggers:
  on_start: # performed when the program is first run
    mining: # specifies that the ship group "mining" is to be controlled
      concurrent: true # Run the actions for each ship at the same time (default is one after another)
      steps: # what to perform to each ship
        - navigate:
            destination:
              type: "ASTEROID_FIELD"
        - action: # Execute the action named "mine"
            name: mine
            repeat:
              interval: 68 # interval in seconds

#  condition:
#    type: greater
#    first:
#      variable: CREDITS
#    second: 100000